'use strict';
const assert=require('assert').strict;require('./battle.test');
describe('Latest fifteen-species metadata',()=>{
 for(const[species,slot,id,component]of [['emboar','0','stokebelly','gluttony'],['mrmime','0','invisiblewall','soundproof'],['barraskewda','1','pursuitwake','infiltrator'],['golurk','0','sentinelfist','ironfist'],['drampa','H','gentlegiant','cloudnine'],['tauros','1','rousingfeast','gluttony'],['hawlucha','0','ringcraft','limber'],['centiskorch','1','constrictingheat','whitesmoke'],['conkeldurr','0','voidreprisal','guts'],['conkeldurr','H','wreckingcrew','ironfist']])it(species+' '+slot+' distribution and identity',()=>{const a=Dex.abilities.get(id);assert.equal(Dex.species.get(species).abilities[slot],a.name);if (['chargedtail','invisiblewall','baitedbloom'].includes(id) && ['static','soundproof','stickyhold'].includes(component)) {assert(Dex.species.get(species).passives.includes(component));assert(!Dex.getAbilityEffects(id).has(component));} else assert(Dex.getAbilityEffects(id).has(component));assert(a.desc.length>40);assert(a.shortDesc.length<160);});
 it('preserves all Tauros breed hidden abilities',()=>{for(const[id,h]of [['tauros','Brute Force'],['taurospaldeacombat','Ultra Ego'],['taurospaldeablaze','Fire Mane'],['taurospaldeaaqua','Thick Fat']])assert.deepEqual(Dex.species.get(id).abilities,{0:'Bull Rush',1:'Rousing Feast',H:h});});
 it('keeps refined signatures in their existing slots',()=>{for(const[id,slot,name]of [['skarmory','0','Fresh Plumage'],['mienshao','H','Meridian Seal'],['kilowattrel','0','Wind Power'],['frosmoth','1','Silk Ward'],['seismitoad','H','Marsh Conduit'],['scolipede','0','Venom Spurs']])assert.equal(Dex.species.get(id).abilities[slot],name);});
});

describe('Archeops approved metadata',()=>{it('retains all slots and describes the once-per-battle recovery and per-move Frenzy',()=>{assert.deepEqual(Dex.species.get('archeops').abilities,{0:'Defeatist',1:'Relic Instinct',H:'Fossil Frenzy'});assert(Dex.abilities.get('relicinstinct').desc.includes('60% maximum HP'));assert(Dex.abilities.get('relicinstinct').desc.includes('Once per Pokemon per battle'));assert(Dex.abilities.get('fossilfrenzy').desc.includes('Once per opposing damaging move'));});});
