'use strict';
const assert=require('assert').strict,fs=require('fs'),path=require('path');require('./battle.test');
global.BattleMovedex=require('../play.pokemonshowdown.com/data/moves.js').BattleMovedex;
const {BattleTooltips,ModifiableValue}=new Function(fs.readFileSync(path.join(__dirname,'../play.pokemonshowdown.com/js/battle-tooltips.js'),'utf8')+'\nreturn {BattleTooltips,ModifiableValue};')();
describe('Starter passive client metadata and previews',()=>{
 it('publishes family rows for ordinary, Mega, Ash, and regional forms without selectable passive slots',()=>{
  for(const [id,expected] of Object.entries({charizard:['blaze'],charizardmegax:['blaze','proficient'],venusaur:['overgrow'],blastoise:['torrent'],greninjabond:['torrent'],greninjaash:['torrent','proficient'],decidueyehisuialt:['overgrow'],skeledirgeaevian:['blaze']}))assert.deepEqual(Dex.species.get(id).passives,expected,id);
  const root=path.join(__dirname,'../play.pokemonshowdown.com');
  const builder=fs.readFileSync(path.join(root,'js/client-teambuilder.js'),'utf8');assert(builder.includes('renderStarterPassives(this.curTeam.dex.species.get(set.species))'));assert(builder.includes('renderStarterPassives(this.curTeam.dex.species.get(selected.species || selected.name))'));
  assert(fs.readFileSync(path.join(root,'js/battle-tooltips.js'),'utf8').includes('pokemon-passives'));
 });
 it('synchronizes all 76 starter records and 31 Proficient gimmick forms without selectable passive slots',()=>{const rows=Object.entries(require('../server-data-sync-manifest.json').snapshot.species).filter(([id,s])=>s.passives?.some(p=>['overgrow','blaze','torrent'].includes(p)));const canonical=id=>({emboaralt:'emboarreborn',emboarmegaalt:'emboarmegareborn'}[id]||id);assert.equal(new Set(rows.map(([id])=>canonical(id))).size,76);assert.deepEqual(Dex.species.get('emboaralt').passives,Dex.species.get('emboarreborn').passives);assert.equal(new Set(rows.filter(([id,s])=>s.passives.includes('proficient')).map(([id])=>canonical(id))).size,31);for(const[id,s]of rows){assert.deepEqual(Dex.species.get(id).passives,s.passives,id);assert.deepEqual(Dex.species.get(id).abilities,s.abilities,id);}for(const id of ['Mew','Pikachu','Bulbasaur','Charmeleon','Wartortle'])assert.deepEqual(Dex.species.get(id).passives,[]);assert.deepEqual(Dex.getAbilityDisplayComponents('atrocity').map(id=>Dex.abilities.get(id).name),['Unbound Blaze','Tough Claws']);});
 it('shows a single Proficient power boost under suppression without altering raw attack stats',()=>{const battle=new Battle({debug:true,log:['|init|battle','|gen|9','|gametype|singles','|switch|p1a: Charizard|Charizard-Mega-X, L100|100/100','|switch|p2a: Mew|Mew, L100|100/100']});const p=battle.p1.active[0],own={speciesForme:'Charizard-Mega-X',ability:'Proficient',baseAbility:'Proficient',passives:['blaze','proficient'],item:'',hp:25,maxhp:100,level:100,status:'',stats:{atk:100,def:100,spa:100,spd:100,spe:100}},tips=new BattleTooltips(battle);try{const m=Dex.moves.get('flamethrower');const power=()=>tips.getMoveBasePower(m,m.type,new ModifiableValue(battle,p,own),battle.p2.active[0]).value;assert.equal(power(),117);p.volatiles.gastroacid=['gastroacid'];assert.equal(power(),117);assert.equal(tips.calculateModifiedStats(p,own).spa,100);own.passives=['blaze'];assert.equal(power(),90);assert.equal(tips.calculateModifiedStats(p,own).spa,100);}finally{battle.destroy();}});
});
